/** Declaration file generated by dts-gen */

export = progress_stream;

declare function progress_stream(options: any, onprogress: any): any;

declare namespace progress_stream {
    const prototype: {
    };

}

